Add initial code to process fill level
waterloo-rocketry/cansw_fillsensing pull request #1
Opened 2020-07-19 21:27 UTC by wendi-yu

Adds the initial `main.c` file that has the code to process changes to fill level. The code is pretty simple, it uses falling-edge interrupt on change signals to detect when a hall sensor has been triggered, and updates the `fill_level` accordingly, based on which sensor fired. 

I'm not entirely sure what to do about the mcc generated files, I don't actually use any of the provided functions (or need them, it seems like?) but it also won't build without the include.

2020-08-06 02:07 UTC, zx100x100 requested changes
looks good, I've tested it on my hardware and it seems to work. 
At some point you may want to move a lot of this to a separate file from main.

2020-08-06 02:07 UTC, zx100x100 commented on main.c
> +#define _XTAL_FREQ 1000000
I assume the 1 MHz XTAL_FREQ is because you have yet to add code to use the external oscillator, add a TODO to init the external oscillator, when that is implemented don't forget to up this to 12MHz.

2020-08-06 02:07 UTC, zx100x100 commented on main.c
> +#define HALL_1 IOCCF5
I would either rename these, or make it clear in a comment that these are the interrupt flag bits, not the input registers.

2020-08-06 02:07 UTC, zx100x100 commented on main.c
> +#define WHITE LATA3
This use of LED macros is quite clear and not an issue, although I do feel I should point out that the way all of the other cansw projects do it is to define on and off Macros:
// LEDs
#define RED_LED_ON() (LATC7 = 0)
#define RED_LED_OFF() (LATC7 = 1)
#define BLUE_LED_ON() (LATC6 = 0)
#define BLUE_LED_OFF() (LATC6 = 1)
#define WHITE_LED_ON() (LATC5 = 0)
#define WHITE_LED_OFF() (LATC5 = 1)

2020-08-06 02:07 UTC, zx100x100 commented on main.c
> +        BLUE = 1;
I don't mind it for these early tests, but generally avoid using the delay function as it halts the processor, which could make a tricky bug to track down later on.

2020-08-06 02:07 UTC, zx100x100 commented on main.c
> +    if (HALL_1) {
As discussed, there may be a more accurate interpolation algorithm, I would add a TODO to investigate that, but this is good for now.

2020-09-29 18:32 UTC, wendi-yu commented
I think all the comments in the scope of this PR have been addressed :)

2020-10-04 23:22 UTC, jacobdeery reviewed
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1)* status: 0 of 19 files reviewed, 11 unresolved discussions (waiting on @jacobdeery, @wendi-yu, and @zx100x100)

___
*[.gitignore, line 22 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MCdRNpl0u0qrQglZuSI:-MCdRNpl0u0qrQglZuSJ:b9nc21m) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/63654af6fad449ffa83b284dc804463a0413afd3/.gitignore#L22)):*
<details><summary><i alt="summary">Quoted 22 lines of code…</i></summary>

> ```
> *.d
> *.pre
> *.p1
> *.lst
> *.sym
> *.obj
> *.o
> *.sdb
> *.obj.dmp
> fillsensing_sw.X/html/
> fillsensing_sw.X/nbproject/private/
> fillsensing_sw.X/nbproject/Package-*.bash
> fillsensing_sw.X/build/
> fillsensing_sw.X/nbbuild/
> fillsensing_sw.X/dist/
> fillsensing_sw.X/nbdist/
> nbactions.xml
> nb-configuration.xml
> funclist
> fillsensing_sw.X/nbproject/Makefile-*
> disassembly/
> *.map
> ```
</details>

Can you break this up into sections based on the type of file? Makes it easier to scan through and see what we're ignoring.
___
*[leds.h, line 26 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MIpu_qu1N81gFIumxeD:-MIpu_qu1N81gFIumxeE:b-mdxfde) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/ab08893a05e65a3ab4fc98411f0b9d5fe749eca2/leds.h#L26)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> #ifdef	__cplusplus
> extern "C" {
> #endif
> #ifdef	__cplusplus
> }
> #endif
> ```
</details>

what's this for?
___
*[leds.c, line 10 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MIpudW05ZYlPsXg2qrG:-MIpudW05ZYlPsXg2qrH:b-m46zb5) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/ab08893a05e65a3ab4fc98411f0b9d5fe749eca2/leds.c#L10)):*
> ```
> RED = RED == 1 ? 0 : 1;
>             WHITE = WHITE == 1 ? 0 : 1;
> ```
```
RED = !RED;
WHITE= !WHITE;
```
___
*[main.c, line 70 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MIpuq6gEIHbxMSG0Tzo:-MIpuq6gEIHbxMSG0Tzp:bc68go8) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/ab08893a05e65a3ab4fc98411f0b9d5fe749eca2/main.c#L70)):*
> ```
> BLUE = BLUE == 1 ? 0 : 1;
> ```
`BLUE = ! BLUE`
___
*[process_fill.h, line 39 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MIputAa7Vik_5G-pvbf:-MIputAa7Vik_5G-pvbg:bypf0um) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/ab08893a05e65a3ab4fc98411f0b9d5fe749eca2/process_fill.h#L39)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> #ifdef	__cplusplus
> extern "C" {
> #endif
> #ifdef	__cplusplus
> }
> #endif
> ```
</details>

What's this for?
___
*[process_fill.c, line 6 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MIpuw5r9cWj8cInui2c:-MIpuw5r9cWj8cInui2d:bb7od0r) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/ab08893a05e65a3ab4fc98411f0b9d5fe749eca2/process_fill.c#L6)):*
> ```C
> void update_fill(volatile uint8_t* fill, uint8_t new_fill) {
>     // indicator LED
>     RED = RED == 1 ? 0 : 1;
> ```

same


<!-- Sent from Reviewable.io -->

2020-10-04 23:36 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1)* status: 0 of 19 files reviewed, 11 unresolved discussions (waiting on @jacobdeery, @wendi-yu, and @zx100x100)

___
*[.gitignore, line 22 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MCdRNpl0u0qrQglZuSI:-MIpyBvU3qDlTnTpg7WV:b-c18zrl) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/63654af6fad449ffa83b284dc804463a0413afd3/.gitignore#L22)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> *.d
> *.pre
> *.p1
> *.lst
> *.sym
> *.obj
> *.o
> *.sdb
> *.obj.dmp
> fillsensing_sw.X/html/
> fillsensing_sw.X/nbproject/private/
> fillsensing_sw.X/nbproject/Package-*.bash
> fillsensing_sw.X/build/
> fillsensing_sw.X/nbbuild/
> fillsensing_sw.X/dist/
> fillsensing_sw.X/nbdist/
> nbactions.xml
> nb-configuration.xml
> funclist
> fillsensing_sw.X/nbproject/Makefile-*
> disassembly/
> *.map
> ```
Can you break this up into sections based on the type of file? Makes it easier to scan through and see what we're ignoring.
</blockquote></details>

Yeah, also removed some of the ignores we don't need for now.
___
*[leds.h, line 26 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MIpu_qu1N81gFIumxeD:-MIpvhBr3z7xgNfXXoVH:b-er0ldu) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/ab08893a05e65a3ab4fc98411f0b9d5fe749eca2/leds.h#L26)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> #ifdef	__cplusplus
> extern "C" {
> #endif
> #ifdef	__cplusplus
> }
> #endif
> ```
what's this for?
</blockquote></details>

I don't actually know, the IDE plopped them in for me lmao. I'll take them out :)
___
*[leds.c, line 10 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MIpudW05ZYlPsXg2qrG:-MIpxDgU9G8W5j1KrXVu:b-896fix) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/ab08893a05e65a3ab4fc98411f0b9d5fe749eca2/leds.c#L10)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> RED = RED == 1 ? 0 : 1;
>             WHITE = WHITE == 1 ? 0 : 1;
> ```
```
RED = !RED;
WHITE= !WHITE;
```
</blockquote></details>

Done.
___
*[main.c, line 4 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MCdRI-i6t4Gzdj_Mz60-r2-4:-MIpvq7s3wwXhNe4gem7:b-896fix) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/63654af6fad449ffa83b284dc804463a0413afd3/main.c#L4)):*
<details><summary><i>Previously, zx100x100 (Zachariah Mears) wrote…</i></summary><blockquote>

I would either rename these, or make it clear in a comment that these are the interrupt flag bits, not the input registers.
</blockquote></details>

Done.
___
*[main.c, line 20 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MCdRI-i6t4Gzdj_Mz60-r2-20:-MIpvsa06E7uIBV_Lb60:b7h283i) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/63654af6fad449ffa83b284dc804463a0413afd3/main.c#L20)):*
<details><summary><i>Previously, zx100x100 (Zachariah Mears) wrote…</i></summary><blockquote>

This use of LED macros is quite clear and not an issue, although I do feel I should point out that the way all of the other cansw projects do it is to define on and off Macros:
// LEDs
#define RED_LED_ON() (LATC7 = 0)
#define RED_LED_OFF() (LATC7 = 1)
#define BLUE_LED_ON() (LATC6 = 0)
#define BLUE_LED_OFF() (LATC6 = 1)
#define WHITE_LED_ON() (LATC5 = 0)
#define WHITE_LED_OFF() (LATC5 = 1)
</blockquote></details>

We only ever toggle so I took out the on/off macros since we don't seem to need them for now 
___
*[main.c, line 37 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MCdRI-i6t4Gzdj_Mz60-r2-37:-MIpvxzU3_l0m_8SlIF3:bodesk3) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/63654af6fad449ffa83b284dc804463a0413afd3/main.c#L37)):*
<details><summary><i>Previously, zx100x100 (Zachariah Mears) wrote…</i></summary><blockquote>

I don't mind it for these early tests, but generally avoid using the delay function as it halts the processor, which could make a tricky bug to track down later on.
</blockquote></details>

Done. Replaced with millis() and fixed the broken millis() from before 
___
*[main.c, line 81 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MCdRI-i6t4Gzdj_Mz60-r2-81:-MIpvzAf6XMKdsmKfcEI:b-896fix) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/63654af6fad449ffa83b284dc804463a0413afd3/main.c#L81)):*
<details><summary><i>Previously, zx100x100 (Zachariah Mears) wrote…</i></summary><blockquote>

As discussed, there may be a more accurate interpolation algorithm, I would add a TODO to investigate that, but this is good for now.
</blockquote></details>

Done.
___
*[main.c, line 70 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MIpuq6gEIHbxMSG0Tzo:-MIpvzmp5p2uf7moJe3m:b-896fix) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/ab08893a05e65a3ab4fc98411f0b9d5fe749eca2/main.c#L70)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> BLUE = BLUE == 1 ? 0 : 1;
> ```
`BLUE = ! BLUE`
</blockquote></details>

Done.
___
*[process_fill.h, line 39 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MIputAa7Vik_5G-pvbf:-MIpw-i_1y4yKCtUsLbG:bkjx6w1) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/ab08893a05e65a3ab4fc98411f0b9d5fe749eca2/process_fill.h#L39)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> #ifdef	__cplusplus
> extern "C" {
> #endif
> #ifdef	__cplusplus
> }
> #endif
> ```
What's this for?
</blockquote></details>

also mplab provided, took it out
___
*[process_fill.c, line 6 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MIpuw5r9cWj8cInui2c:-MIpwXuF8h2WDRTxc_bV:b-896fix) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/ab08893a05e65a3ab4fc98411f0b9d5fe749eca2/process_fill.c#L6)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-05 17:32 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1)* status: 0 of 19 files reviewed, 7 unresolved discussions (waiting on @jacobdeery, @wendi-yu, and @zx100x100)

___
*[.gitignore, line 22 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MCdRNpl0u0qrQglZuSI:-MItjV2m-SlA_Fi_x2mK:b-s6doou) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/63654af6fad449ffa83b284dc804463a0413afd3/.gitignore#L22)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Yeah, also removed some of the ignores we don't need for now.
</blockquote></details>

Doesn't seem to be done?
___
*[process_fill.c, line 18 at r5](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MItnzp95u15Q0xX8hpW:-MItnzp95u15Q0xX8hpX:bii5259) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/2cf42e9aab2bcfd0d2df522fef38847e1775aea9/process_fill.c#L18)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> if (HALL_1_FLAG) {
>         HALL_1_FLAG = 0;
>         update_fill(fill, 1);
>     } 
> ```
</details>


you could maybe reduce the repetition here if you stuck all of the `HALL_*_FLAG`s into an array, and then did something like this:

```
for (size_t i = 0; i < NUM_FLAGS; ++i) {
    if (FLAGS[i]) {
        FLAGS[i] = 0;
        update_fill(fill, i);
        return;
    }
}
```


<!-- Sent from Reviewable.io -->

2020-10-26 00:06 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1)* status: 0 of 19 files reviewed, 7 unresolved discussions (waiting on @jacobdeery and @zx100x100)

___
*[.gitignore, line 22 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MCdRNpl0u0qrQglZuSI:-MKXDLA28eNN9mP_N3y_:b-7k6o4m) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/63654af6fad449ffa83b284dc804463a0413afd3/.gitignore#L22)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Doesn't seem to be done?
</blockquote></details>

Removed all the extras this time oops sorry mb
___
*[main.c, line 1 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MCdRI-i6t4Gzdj_Mz60-r2-1:-MKXDKdB0h1g_0Kvc_kO:b-896fix) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/63654af6fad449ffa83b284dc804463a0413afd3/main.c#L1)):*
<details><summary><i>Previously, zx100x100 (Zachariah Mears) wrote…</i></summary><blockquote>

I assume the 1 MHz XTAL_FREQ is because you have yet to add code to use the external oscillator, add a TODO to init the external oscillator, when that is implemented don't forget to up this to 12MHz.
</blockquote></details>

Done.
___
*[process_fill.c, line 18 at r5](https://reviewable.io/reviews/waterloo-rocketry/cansw_fillsensing/1#-MItnzp95u15Q0xX8hpW:-MKXDOZPD1bi22Dsul8M:b-yvyso1) ([raw file](https://github.com/waterloo-rocketry/cansw_fillsensing/blob/2cf42e9aab2bcfd0d2df522fef38847e1775aea9/process_fill.c#L18)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> if (HALL_1_FLAG) {
>         HALL_1_FLAG = 0;
>         update_fill(fill, 1);
>     } 
> ```

you could maybe reduce the repetition here if you stuck all of the `HALL_*_FLAG`s into an array, and then did something like this:

```
for (size_t i = 0; i < NUM_FLAGS; ++i) {
    if (FLAGS[i]) {
        FLAGS[i] = 0;
        update_fill(fill, i);
        return;
    }
}
```
</blockquote></details>

Will address later as discussed, after working code is ready for static fire :)


<!-- Sent from Reviewable.io -->

2020-10-27 03:48 UTC, zx100x100 approved these changes
Only one small comment, generally looks good

2020-10-27 03:48 UTC, zx100x100 commented on main.c
> +    IOCBN = 0b11111111;
It seems a little interesting that you are enabling the interupt on change for RB6 and RB7, which aren't used.

2020-10-28 16:50 UTC, merged